### PR TITLE
Compat dplyr 0.6.0

### PR DESCRIPTION
**Pull request by lionel-**
The plan is to prepare the release in https://github.com/tidyverse/purrr/tree/release-0.2.2.1 and merge that branch in master afterwards. Could you please check the revdep email to check that everything is clear @hadley?

### CODE REVIEW

**Comment by lionel-** [comment]
yes that'd be better. Most problems come from `map_df()` as the dplyr dep does not transit though purrr anymore, but one package (GGally) requires `dmap()`.

**Comment by hadley** [comment]
Looks good. 

Let's aim for release on Monday — can you apologise for the short-notice, but comment that it should only require one of two changes (i.e. importing dplyr or importing purrrlyr), and that we need it for dplyr.

**Comment by hadley** [comment]
Can you please notify everyone today?

**Comment by lionel-** [comment]
Will do.

**Pull request merged**
