### PR TITLE
replaced quote by tick mark

### PR DESCRIPTION
**Pull request by EdwinTh**
_list-elements_ was between a tick mark and a quote. From the context it seems like it should be between tick marks.

### CODE REVIEW

**Comment by lionel-** [comment]
Could you reoxygenise as well please?

**Comment by EdwinTh** [comment]
Sure. However it seems that the documentation of a whole bunch of functions needs to be reoxygenised as well (everywhere `code{}` is replaced by tick marks). It doesn't seem appropriate to have them in the PR.

**Comment by lionel-** [comment]
If you use the same roxygen version as the project uses there shouldn't be any problem.

I think purrr is using CRAN roxygen so no worries there, otherwise you can install a specific version with `install_github("klutometis/roxygen", ref = "v6.0.1")`.

**Comment by EdwinTh** [comment]
Thanks, I indeed had to update my roxygen

**Comment by lionel-** [comment]
Thanks!

**Pull request merged**
