### PR TITLE
Add modify methods for integer, double, and character

### PR DESCRIPTION
**Pull request by t-kalinowski**
`modify` methods for integer, double and character, to complement `map_int` `map_dbl` and `map_chr`.

### CODE REVIEW

**Comment by hadley** [comment]
Can you please:

* Merge/rebase
* Add logical methods to complete the set
* Add a few tests of basic functionality (i.e. one test for each `modify_` function, checking that the type of atomic vector is preserved, e.g. `expect_type(modify("a", identity), "character")`)

**Comment by hadley** [comment]
Fixes #417

**Comment by t-kalinowski** [comment]
Rebased on the current master branch and comments are addressed. The test fails for an unrelated reason (`as_mapper`).

**Comment by hadley** [comment]
Can you please merge/rebase? Sorry for breaking `as_mapper()`

**Comment by t-kalinowski** [comment]
Ok, please take a look.

**Comment by hadley** [comment]
Something has gone wrong with your merge/rebase - there shouldn't be commits from me in this branch. @jimhester can you please take a look when you have a minute?

**Comment by t-kalinowski** [comment]
submitted a new PR with a clean history #463

**Pull request closed without merging**
