### PR TITLE
Split by

### PR DESCRIPTION
**Pull request by t-kalinowski**
Hello,

This is a proposal for a companion to `map_dfr()` that's a little easier to work with than than `base::split()`. 

If there is interest, I would be happy to add tests and flesh out the docs a bit.

### CODE REVIEW

**Comment by yutannihilation** [comment]
For your information, another `split_by()` had been implemented once and was removed on version 0.2.3. (The semantic seems different than yours, though)

* https://github.com/tidyverse/purrr/blob/master/NEWS.md#purrr-023
* https://www.rdocumentation.org/packages/purrr/versions/0.2.2/topics/split_by

**Comment by cderv** [comment]
For reference, `split_by` has been removed as result of #217 in https://github.com/tidyverse/purrr/commit/7dc96a8dd1e257a2c16f91901912c9c0e6c2fc1c.

For information too, some functions at the intersection of `purrr` and `dplyr` has been moved to [purrrlyr](https://github.com/hadley/purrrlyr). Your idea may belong there.

* See [NEWS.md](https://github.com/tidyverse/purrr/blob/master/NEWS.md#purrr-0221) of 0.2.2.1 version
* See documentation of `purrrlyr` on [rdocumentation](https://www.rdocumentation.org/packages/purrrlyr/versions/0.0.2/)

**Comment by t-kalinowski** [comment]
Thank you @yutannihilation and @cderv, I wasn't aware (or had forgotten) that a function named `split_by()` had existed at one point. What I'm proposing here seems quite different from that function though. Perhaps a different name is needed.  

Also, I might be mistaken, but the fact that `purrrlyr` is not part of the tidyverse suggests that `purrrlyr` not being actively developed anymore, in favor of `purrr` and `dplyr`.

**Comment by hadley** [comment]
Yeah, this doesn't feel quite right for purrr to me.

**Comment by t-kalinowski** [comment]
Ok, Thanks for considering.

As I've been using `split_by` more and more, I find it's much easier to work with than the alternatives. `do()` is confusing, clunky, and limiting. (it wasn't until I read the source that I realized that `.` is not evaluated by magrittr as a pipe, but is actually an active binding that evaluates to each subset)

 and `nest() + `mutate(... map(data, ...))` is powerful for when you need it but it's a lot of syntax and infrastructure to write and sometimes you just want a lighter-weight solution. (also, it's limiting in it's own way because you don't have straightforward access to the grouping variable within the function you're mapping, forcing you to pass it in as a separate named argument... again leading to more verbose syntax)

The best alternative then is `base::split`, which works great when splitting on one variable
``` df %>% split(.$var1) %>% map(fun)```
 but that suddenly requires a lot of syntax if you're splitting on more than one variable
`df %>% split(list(.$var1, .$var2), drop = TRUE)) %>% map(fun)`

Hence this pull request.

I agree it's not very purrr-like since it operates on bare symbols, but I do think there is a missing piece here in terms of functionality.

**Pull request closed without merging**
