### PR TITLE
minimal support for raw, e.g. `map_raw`, `map2_raw`, `imap_raw`, `fla…

### PR DESCRIPTION
**Pull request by romainfrancois**
…tten_raw`

I have a potential use case for `map_raw` to eliminate e.g. this `sapply` : https://github.com/ThinkRstat/tipixel/blob/master/R/generate_base.R#L22

### CODE REVIEW

**Comment by romainfrancois** [comment]
I added a bunch of tests and some support for coercion as well: 

```
> raws <- as.raw(0:2)
> map( raws, 1)
[[1]]
[1] 00

[[2]]
[1] 01

[[3]]
[1] 02

> map_raw(raws, 1)
[1] 00 01 02
> map_int(raws, 1)
[1] 0 1 2
> map_dbl(raws, 1)
[1] 0 1 2
> map_chr(raws, 1)
[1] "00" "01" "02"
```

**Comment by hadley** [comment]
Can you please merge/rebase and take a look at improving the test coverage?

**Comment by hadley** [comment]
Looks like something went wrong with the merge - there are a lot of spurious diffs

**Comment by romainfrancois** [comment]
yeah that's weird. I'll make another cleaner pr.

**Pull request closed without merging**
