### PR TITLE
Standardise `_if` & `_at` helpers

### PR DESCRIPTION
**Pull request by hadley**
* `probe()` -> `where_if()`
* `at_selection()` -> `where_at()`

`where_at()` now generates a logical vector directly, rather than going through `inv_which()`.

---

@DavisVaughan the most useful feedback would be on the names.

### CODE REVIEW

**Review by DavisVaughan — APPROVED** [review]
For vctrs functions that return logical vectors the same size as `x`, we use the verb `detect`, like `vec_detect_complete()`

So I might do something like:

```r
where_if -> detect_predicate (somewhat nice because internally it calls `as_predicate`)
where_at -> detect_at
```

Using `where` as the name of the returned logical vector seems fine, I don't have a better name for that

**Comment by hadley** [comment]
We could rename `as_predicate` to `as_if()` 😆

**Comment by DavisVaughan** [comment]
`detect_names()` feels a little weird because it allows numeric indices too. `detect_location()`? To go with the fact that it calls `vec_as_location()`?

**Comment by hadley** [comment]
I think I'll just keep them as is — they're internal helpers, the names here are already substantially better, and I'm worried that `detect_*` is too confusing given the other exported `detect()` functions.

**Pull request merged**
